### ISSUE TITLE
nwb_gui not working

### ISSUE THREAD

**Issue by bendichter** [rly/buffalo-lab-data-to-nwb#20]
```python
Traceback (most recent call last):
  File "src/buffalonwb/nwb_gui.py", line 25, in <module>
    source_paths=source_paths, kwargs_fields=kwargs_fields)
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/nwbn_conversion_gui.py", line 608, in nwbn_conversion_gui
    show_add_del=show_add_del)
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/nwbn_conversion_gui.py", line 50, in __init__
    self.load_meta_file(filename=metafile)
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/nwbn_conversion_gui.py", line 351, in load_meta_file
    self.update_forms()
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/nwbn_conversion_gui.py", line 484, in update_forms
    write_data=self.metadata[grp][subgroup])
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/classes/forms_behavior.py", line 649, in add_group
    item.write_fields(data=write_data)
  File "/Users/bendichter/dev/nwbn-conversion-tools/nwbn_conversion_tools/gui/classes/forms_behavior.py", line 577, in write_fields
    item = GroupSpatialSeries(self, metadata=data['spatial_series'][ind])
KeyError: 0
```

**Comment by luiztauffer** [comment]
fix wit #21
